name: Build VST3
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Loudness Catalyst on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup JUCE
        run: |
          git clone --depth 1 https://github.com/juce-framework/JUCE.git
        shell: bash

      - name: Configure CMake
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cmake -B build -A x64 -D JUCE_PATH=./JUCE -D CMAKE_BUILD_TYPE=Release
          else
            cmake -B build -D JUCE_PATH=./JUCE -D CMAKE_BUILD_TYPE=Release
          fi
        shell: bash

      - name: Build Plugin
        run: cmake --build build --config Release --target LoudnessCatalyst_VST3 --parallel 4 --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoudnessCatalyst-${{ runner.os }}
          path: |
            build/**/*.vst3
          if-no-files-found: error
